# Generated by Django 3.2.8 on 2021-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(default='', max_length=30)),
                ('isopioid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pd_drugs',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=11)),
                ('lname', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=1)),
                ('state', models.CharField(max_length=2)),
                ('credentials', models.CharField(blank=True, max_length=20)),
                ('specialty', models.CharField(max_length=62)),
                ('isopioidprescriber', models.BooleanField(default=False)),
                ('totalprescriptions', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_Prescriber',
            },
        ),
    ]
