<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-12-02 16:56
=======
# Generated by Django 3.2.8 on 2021-12-02 17:44
>>>>>>> 21debc32487962fb1896cda2e5681f5fff4dc4c0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugId', models.IntegerField(unique=True)),
                ('drugname', models.CharField(default='', max_length=30)),
                ('isopioid', models.CharField(default='', max_length=5)),
            ],
            options={
                'db_table': 'pd_drugs',
=======
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=11)),
                ('lname', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=1)),
                ('state', models.CharField(max_length=2)),
                ('credentials', models.CharField(blank=True, max_length=20)),
                ('specialty', models.CharField(max_length=62)),
                ('isopioidprescriber', models.BooleanField(default=False)),
                ('totalprescriptions', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_Prescriber',
>>>>>>> 21debc32487962fb1896cda2e5681f5fff4dc4c0
            },
        ),
    ]
