# Generated by Django 3.2.9 on 2021-12-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugId', models.IntegerField(unique=True)),
                ('drugname', models.CharField(default='', max_length=30)),
                ('isopioid', models.CharField(default='', max_length=5)),
            ],
            options={
                'db_table': 'pd_drugs',
            },
        ),
    ]
