# Generated by Django 3.2.9 on 2021-12-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='isopioid',
            field=models.CharField(max_length=5),
        ),
    ]
