# Generated by Django 3.2.8 on 2021-12-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_drug_isopioid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prescriber',
            table='pd_prescriber',
        ),
    ]
