# Generated by Django 3.2.9 on 2021-12-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_drug_drugid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='drugId',
        ),
    ]
