# Generated by Django 3.2.9 on 2021-12-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_drug_drugid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='isopioid',
            field=models.BooleanField(default=False),
        ),
    ]
