# Generated by Django 3.2.9 on 2021-12-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_prescriber_table'),
        ('homepage', '0003_auto_20211203_2009'),
    ]

    operations = [
    ]
