# Generated by Django 3.2.9 on 2021-12-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_triple_prescriberid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='triple',
            table='pd_triples',
        ),
    ]
