# Generated by Django 3.2.9 on 2021-12-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_triple_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='triple',
            table='pd_triples',
        ),
    ]
