# Generated by Django 3.2.9 on 2021-12-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_triple_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prescriber',
            table='pd_prescribers',
        ),
    ]
